matrix:
  include:
    - os: linux
      dist: trusty
      language: python
      python: "3.5"
    - os: osx
      osx_image: xcode8.3
      language: generic

# install boost on linux only (already here on osx)
addons:
  apt:
    packages:
      - libboost-program-options-dev

# install python3 on osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv --python=python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi

install:
  - pip install --upgrade pip
  - pip install pandas numpy>=1.13 cython pytest h5py h5features 
  - pip install http://download.pytorch.org/whl/cu75/torch-0.2.0.post3-cp35-cp35m-manylinux1_x86_64.whl 
  - pip install torchvision
  - python setup.py build
  - python setup.py install

script:
  - pytest ./test

cache:
  - pip

notifications:
  email: false
  