name: abnet
channels:
  - soumith
  - defaults
dependencies:
  - python=3.6
  - matplotlib
  - pyyaml
  - numpy=1.*
  - cython
  - h5py=2.*
  - pytest
  - numpydoc
  - scipy>=0.13.*
  - pytorch=0.2.0
  - pip:
    - tensorboardX==1.0
